# ModelArguments
model_name_or_path: "allenai/PRIMERA-multixscience"

# DataTrainingArguments
dataset_name: "multi_x_science_sum"
text_column: "abstract"
summary_column: "related_work"
max_source_length: 4096
max_target_length: 1024

# Seq2SeqTrainingArguments
do_train: true
do_eval: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 12
gradient_accumulation_steps: 16
learning_rate: 3e-5
num_train_epochs: 1
warmup_ratio: 0.10