# ModelArguments
model_name_or_path: "google/pegasus-multi_news"

# DataTrainingArguments
dataset_name: "multi_news"
max_source_length: 1024
max_target_length: 512

# Seq2SeqTrainingArguments
do_train: true
do_predict: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 3e-5
num_train_epochs: 1
warmup_ratio: 0.10
